from PyQt5 import QtCore, QtGui, QtWidgets


class Screen(object):
    def __init__(self):
        self.volume = None
        self.feedback = None
        self.back_about = None
        self.about_image = None
        self.about_page = None
        self.current_player = None
        self.back_player = None
        self.add_player = None
        self.add_btn_layout = None
        self.layoutWidget_4 = None
        self.add_buttons = None
        self.add_card = None
        self.verticalLayout = None
        self.verticalLayoutWidget = None
        self.scroll_widget = None
        self.scroll_area = None
        self.players_page = None
        self.game_area = None
        self.scores_image = None
        self.line = None
        self.highscore = None
        self.score = None
        self.play_page = None
        self.back_difficulty = None
        self.extreme = None
        self.hard = None
        self.medium = None
        self.easy = None
        self.verticalLayout_2 = None
        self.layoutWidget = None
        self.difficulty_image = None
        self.difficulty_page = None
        self.about = None
        self.players = None
        self.play = None
        self.main_menu_img = None
        self.main_page = None
        self.stackedWidget = None
        self.centralwidget = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 711, 801))
        self.stackedWidget.setStyleSheet("#play_page {background-color: black;}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.main_menu_img = QtWidgets.QLabel(self.main_page)
        self.main_menu_img.setGeometry(QtCore.QRect(0, 0, 708, 800))
        self.main_menu_img.setStyleSheet("background-image: url(:/Images/Images/main_menu.png);")
        self.main_menu_img.setText("")
        self.main_menu_img.setObjectName("main_menu_img")
        self.play = QtWidgets.QPushButton(self.main_page)
        self.play.setGeometry(QtCore.QRect(90, 490, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        self.play.setFont(font)
        self.play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play.setObjectName("play")
        self.players = QtWidgets.QPushButton(self.main_page)
        self.players.setGeometry(QtCore.QRect(90, 575, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        self.players.setFont(font)
        self.players.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.players.setObjectName("players")
        self.about = QtWidgets.QPushButton(self.main_page)
        self.about.setGeometry(QtCore.QRect(90, 660, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        self.about.setFont(font)
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about.setObjectName("about")
        
        self.volume = QtWidgets.QPushButton(self.main_page)
        self.volume.setGeometry(QtCore.QRect(650, 30, 41, 41))
        self.volume.setStyleSheet("")
        self.volume.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/volume-high.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.volume.setIcon(icon)
        self.volume.setIconSize(QtCore.QSize(30, 30))
        self.volume.setCheckable(True)
        self.volume.setObjectName("volume")
    
        self.stackedWidget.addWidget(self.main_page)
        self.difficulty_page = QtWidgets.QWidget()
        self.difficulty_page.setObjectName("difficulty_page")
        self.difficulty_image = QtWidgets.QLabel(self.difficulty_page)
        self.difficulty_image.setGeometry(QtCore.QRect(0, -5, 708, 810))
        self.difficulty_image.setStyleSheet("background-image: url(:/Images/Images/difficulty.png);")
        self.difficulty_image.setText("")
        self.difficulty_image.setObjectName("difficulty_image")
        self.layoutWidget = QtWidgets.QWidget(self.difficulty_page)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 250, 301, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.easy = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.easy.sizePolicy().hasHeightForWidth())
        self.easy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.easy.setFont(font)
        self.easy.setObjectName("easy")
        self.verticalLayout_2.addWidget(self.easy)
        self.medium = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medium.sizePolicy().hasHeightForWidth())
        self.medium.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.medium.setFont(font)
        self.medium.setObjectName("medium")
        self.verticalLayout_2.addWidget(self.medium)
        self.hard = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hard.sizePolicy().hasHeightForWidth())
        self.hard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.hard.setFont(font)
        self.hard.setObjectName("hard")
        self.verticalLayout_2.addWidget(self.hard)
        self.extreme = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extreme.sizePolicy().hasHeightForWidth())
        self.extreme.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.extreme.setFont(font)
        self.extreme.setObjectName("extreme")
        self.verticalLayout_2.addWidget(self.extreme)
        self.back_difficulty = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_difficulty.sizePolicy().hasHeightForWidth())
        self.back_difficulty.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.back_difficulty.setFont(font)
        self.back_difficulty.setObjectName("back_difficulty")
        self.verticalLayout_2.addWidget(self.back_difficulty)
        self.stackedWidget.addWidget(self.difficulty_page)
        self.play_page = QtWidgets.QWidget()
        self.play_page.setObjectName("play_page")
        self.score = QtWidgets.QLabel(self.play_page)
        self.score.setGeometry(QtCore.QRect(30, 25, 171, 45))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.score.setFont(font)
        self.score.setStyleSheet("color: rgb(255, 255, 255);")
        self.score.setObjectName("score")
        self.highscore = QtWidgets.QLabel(self.play_page)
        self.highscore.setGeometry(QtCore.QRect(280, 25, 400, 45))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.highscore.setFont(font)
        self.highscore.setStyleSheet("color: rgb(255, 255, 255);")
        self.highscore.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.highscore.setObjectName("highscore")
        self.line = QtWidgets.QLabel(self.play_page)
        self.line.setGeometry(QtCore.QRect(-20, -10, 741, 101))
        self.line.setStyleSheet("border: 1px solid white;")
        self.line.setText("")
        self.line.setObjectName("line")
        self.scores_image = QtWidgets.QFrame(self.play_page)
        self.scores_image.setGeometry(QtCore.QRect(0, 0, 711, 91))
        self.scores_image.setStyleSheet("background-image: url(:/Images/Images/players.png);")
        self.scores_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scores_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scores_image.setObjectName("scores_image")

        self.game_area = QtWidgets.QLabel(self.play_page)
        self.game_area.setGeometry(QtCore.QRect(0, 90, 711, 711))
        self.game_area.setObjectName("game_area")
        self.game_area.setText("")

        self.feedback = QtWidgets.QLabel(self.play_page)
        self.feedback.setGeometry(QtCore.QRect(0, 10, 711, 791))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.feedback.setFont(font)
        self.feedback.setStyleSheet("background-color: rgba(0, 0, 0, 200); color: rgb(255, 255, 255);")
        self.feedback.setAlignment(QtCore.Qt.AlignCenter)
        self.feedback.setObjectName("feedback")

        self.scores_image.raise_()
        self.line.raise_()
        self.score.raise_()
        self.highscore.raise_()
        self.game_area.raise_()
        self.feedback.raise_()
        self.stackedWidget.addWidget(self.play_page)
        self.players_page = QtWidgets.QWidget()
        self.players_page.setStyleSheet("")
        self.players_page.setObjectName("players_page")
        self.scroll_area = QtWidgets.QScrollArea(self.players_page)
        self.scroll_area.setGeometry(QtCore.QRect(0, 10, 711, 791))
        self.scroll_area.setStyleSheet("#scroll_area {border: 0; border-radius:10px;}")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.Box)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_widget = QtWidgets.QWidget(self.scroll_area)
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 690, 791))
        self.scroll_widget.setStyleSheet("#scroll_widget {background-image: url(:/Images/Images/players.png);}")
        self.scroll_widget.setObjectName("scroll_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scroll_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 791))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scroll_widget)
        self.verticalLayout.setContentsMargins(0, 50, 0, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_card = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_card.sizePolicy().hasHeightForWidth())
        self.add_card.setSizePolicy(sizePolicy)
        self.add_card.setMinimumSize(QtCore.QSize(551, 171))
        self.add_card.setMaximumSize(QtCore.QSize(551, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_card.setFont(font)
        self.add_card.setStyleSheet("QGroupBox {border: 1px solid black; border-radius: 10px; margin-top: 10px; "
                                    "background-color: rgb(25, 108, 153); color: white;} "
                                    "QGroupBox::title {subcontrol-origin: margin; left: 50px; "
                                    "padding: 0px 5px 0px 5px;}")
        self.add_card.setAlignment(QtCore.Qt.AlignCenter)
        self.add_card.setObjectName("add_card")
        self.add_buttons = QtWidgets.QLabel(self.add_card)
        self.add_buttons.setGeometry(QtCore.QRect(260, 30, 271, 121))
        self.add_buttons.setStyleSheet("background-image: url(:/Images/Images/players.png);")
        self.add_buttons.setText("")
        self.add_buttons.setObjectName("add_buttons")
        self.layoutWidget_4 = QtWidgets.QWidget(self.add_card)
        self.layoutWidget_4.setGeometry(QtCore.QRect(270, 40, 251, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.add_btn_layout = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.add_btn_layout.setContentsMargins(0, 0, 0, 0)
        self.add_btn_layout.setSpacing(11)
        self.add_btn_layout.setObjectName("add_btn_layout")
        self.add_player = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_player.sizePolicy().hasHeightForWidth())
        self.add_player.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.add_player.setFont(font)
        self.add_player.setObjectName("add_player")
        self.add_btn_layout.addWidget(self.add_player)
        self.back_player = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_player.sizePolicy().hasHeightForWidth())
        self.back_player.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.back_player.setFont(font)
        self.back_player.setObjectName("back_player")
        self.add_btn_layout.addWidget(self.back_player)
        self.current_player = QtWidgets.QLabel(self.add_card)
        self.current_player.setGeometry(QtCore.QRect(20, 30, 201, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.current_player.setFont(font)
        self.current_player.setStyleSheet("border: 0; background-color: rgb(90, 173, 217);")
        self.current_player.setAlignment(QtCore.Qt.AlignCenter)
        self.current_player.setObjectName("current_player")
        self.verticalLayout.addWidget(self.add_card, 0, QtCore.Qt.AlignHCenter)
        self.scroll_area.setWidget(self.scroll_widget)
        self.stackedWidget.addWidget(self.players_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.about_image = QtWidgets.QLabel(self.about_page)
        self.about_image.setGeometry(QtCore.QRect(0, 0, 711, 801))
        self.about_image.setStyleSheet("image: url(:/Images/Images/about.png);")
        self.about_image.setText("")
        self.about_image.setObjectName("about_image")
        self.back_about = QtWidgets.QPushButton(self.about_page)
        self.back_about.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.back_about.setFont(font)
        self.back_about.setObjectName("back_about")
        self.stackedWidget.addWidget(self.about_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "PLAY"))
        self.players.setText(_translate("MainWindow", "PLAYERS"))
        self.about.setText(_translate("MainWindow", "ABOUT"))
        self.easy.setText(_translate("MainWindow", "EASY"))
        self.medium.setText(_translate("MainWindow", "MEDIUM"))
        self.hard.setText(_translate("MainWindow", "HARD"))
        self.extreme.setText(_translate("MainWindow", "EXTREME"))
        self.back_difficulty.setText(_translate("MainWindow", "MAIN MENU"))
        self.score.setText(_translate("MainWindow", "Score: 0"))
        self.highscore.setText(_translate("MainWindow", "Highscore: 0 [Easy]"))
        self.feedback.setText(_translate("MainWindow", "3"))
        self.add_card.setTitle(_translate("MainWindow", "Add Player"))
        self.add_player.setText(_translate("MainWindow", "ADD PLAYER"))
        self.back_player.setText(_translate("MainWindow", "MAIN MENU"))
        self.current_player.setText(_translate("MainWindow", f"Selected Player:\nNone"))
        self.back_about.setText(_translate("MainWindow", "MAIN MENU"))
